apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-storage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/db"